# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7360c7534d475ce341715f74d8c441eb20d5ecb14261161853d08cab47fa23bd66895b6c8dc5455d666e2001ccc3ace2efec34d7304faeafdc9aec45bf64ccfb

test:
  secret_key_base: e441c5171cae5dae6fa36345e06e1d24223692f206a3fe7ab1d4d165496369414e9e05d0802dbaed32b89768e647b534f3108e5fbdafa7b71a67cb007abf8b00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
